version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install curl
          command: apt-get install -y curl

      - run:
          name: Get toolchain
          command: curl https://remarkable.engineering/deploy/sdk/poky-glibc-x86_64-meta-toolchain-qt5-cortexa9hf-neon-toolchain-2.1.3.sh -o install-toolchain.sh

      - run:
          name: Install toolchain
          command: ./install-toolchain.sh

      - run:
          name: Install qtcreator
          command: apt-get install -y qtcreator

      - run:
          name: where are all the files?
          command: ls
