version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: update apt-cache
          command: apt-get update

      - run:
          name: Install curl and xz
          command: apt-get install -y curl xz-utils python git

      - run:
          name: pull submodules
          command: |
            git submodule init
            git submodule update --remote

      - run:
          name: Get toolchain
          command: curl https://remarkable.engineering/deploy/sdk/poky-glibc-x86_64-meta-toolchain-qt5-cortexa9hf-neon-toolchain-2.1.3.sh -o install-toolchain.sh

      - run:
          name: make toolchain executable
          command: chmod +x ./install-toolchain.sh

      - run:
          name: Install toolchain
          command: ./install-toolchain.sh

      - run:
          name: Source toolchain
          command: source /opt/poky/2.1.3/environment-setup-cortexa9hf-neon-poky-linux-gnueabi

      - run:
          name: Install qtcreator
          command: apt-get install -y qtcreator

      - run:
          name: Build
          command: /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qmake -spec linux-oe-g++ -o Makefile edit.pro

      - run:
          name: where are all the files?
          command: find .
